import { memo, useMemo } from "react";
import { resolverLayout, resolverSegmento, useCnab } from "../../contexts/CnabContext";
import * as S from "./styles";
function money(value:string){const digits=value.replace(/\D/g,""); if(!digits) return 0; return Number(digits)/100;}
function fmt(v:number){return v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});}
const AmountValidationPage=memo(function AmountValidationPage(){
 const {banco,linhas,resumoArquivo}=useCnab();
 const rows=useMemo(()=>linhas.flatMap((linha,i)=>(resolverLayout(linha,banco)??[]).filter(c=>/valor|juros|desconto|abatimento|iof|multa/i.test(`${c.label} ${c.descricao??""}`)).map(c=>{const raw=linha.slice(c.inicio-1,c.fim); const invalid=raw.trim()!==""&&!/^[0-9 ]+$/.test(raw); const amount=money(raw); return {linha:i+1,segmento:resolverSegmento(linha,banco),campo:c.label,pos:`${c.inicio}-${c.fim}`,raw,amount,status:invalid?"erro":amount===0?"aviso":"ok" as "ok"|"erro"|"aviso"};})),[banco,linhas]);
 const total=rows.reduce((s,r)=>s+r.amount,0); const erros=rows.filter(r=>r.status==="erro").length; const zeros=rows.filter(r=>r.status==="aviso").length;
 return <S.PageShell><S.PageHeader><S.PageTitleGroup><S.PanelTitle>Validador de valores</S.PanelTitle><S.PageTitle>{resumoArquivo.nome}</S.PageTitle></S.PageTitleGroup><S.SummaryCount>{rows.length} valores</S.SummaryCount></S.PageHeader>{linhas.length===0?<S.EmptyOutput>Carregue ou cole um arquivo CNAB para analisar valores.</S.EmptyOutput>:<><S.SummaryGrid><S.SummaryMetric><S.SummaryMetricLabel>Total interpretado</S.SummaryMetricLabel><S.SummaryMetricValue>{fmt(total)}</S.SummaryMetricValue></S.SummaryMetric><S.SummaryMetric><S.SummaryMetricLabel>Campos zerados</S.SummaryMetricLabel><S.SummaryMetricValue>{zeros}</S.SummaryMetricValue></S.SummaryMetric><S.SummaryMetric><S.SummaryMetricLabel>Inválidos</S.SummaryMetricLabel><S.SummaryMetricValue>{erros}</S.SummaryMetricValue></S.SummaryMetric></S.SummaryGrid><S.TableSection><S.DataTable><S.HeaderRow><S.PlainText>Linha</S.PlainText><S.PlainText>Status</S.PlainText><S.PlainText>Segmento</S.PlainText><S.PlainText>Campo</S.PlainText><S.PlainText>Posição</S.PlainText><S.PlainText>Bruto</S.PlainText><S.PlainText>Valor</S.PlainText></S.HeaderRow>{rows.map((r,idx)=><S.DataRow key={`${r.linha}-${r.campo}-${idx}`}><S.MonoValue>{r.linha}</S.MonoValue><S.StatusBadge $status={r.status}>{r.status}</S.StatusBadge><S.PlainText>{r.segmento}</S.PlainText><S.PlainText>{r.campo}</S.PlainText><S.MonoValue>{r.pos}</S.MonoValue><S.MonoValue>{r.raw||"-"}</S.MonoValue><S.FieldValue>{fmt(r.amount)}</S.FieldValue></S.DataRow>)}</S.DataTable></S.TableSection></>}</S.PageShell>;
});
export default AmountValidationPage;