import styled from "styled-components";
export * from "../../styles";
export const FilePicker=styled.div`display:flex;align-items:center;justify-content:flex-end;`;
export const EmptyState=styled.div`display:grid;min-height:240px;place-items:center;padding:24px;border:1px solid var(--border);border-radius:8px;background:var(--surface);color:var(--muted);font-size:var(--font-md);text-align:center;`;
export const TableSection=styled.section`min-height:0;padding:14px;border:1px solid var(--border);border-radius:8px;background:var(--surface);overflow:auto;`;
export const DataTable=styled.div`display:grid;gap:8px;min-width:1120px;`;
export const DataRow=styled.div`min-height:var(--row-height);display:grid;grid-template-columns:70px 170px 230px 110px minmax(240px,1fr) minmax(240px,1fr);gap:10px;align-items:center;padding:9px 10px;border:1px solid var(--border);border-radius:6px;background:rgba(255,255,255,.02);color:var(--text);font-size:var(--font-sm);&>*{min-width:0;}`;
export const HeaderRow=styled(DataRow)`background:var(--surface-muted);color:var(--muted);font-size:var(--font-xs);font-weight:800;text-transform:uppercase;`;
export const MonoValue=styled.span`font-family:var(--mono);overflow-wrap:anywhere;`;
export const FieldValue=styled(MonoValue)`color:var(--text-strong);white-space:pre;overflow:hidden;text-overflow:ellipsis;`;